[package]
name = "example-api-web-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
example_api_web-core = { package = "example-api-web-core", path = "../example-api-web-core" }
pyo3.workspace = true

[lints]
workspace = true
