[package]
name = "{{ project_name }}-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
{{ module_name }}-core = { package = "{{ project_name }}-core", path = "../{{ project_name }}-core" }
pyo3.workspace = true

[lints]
workspace = true
