class KernformNativeError(Exception): ...
class KernformPolicyError(KernformNativeError): ...
class KernformPreconditionError(KernformNativeError): ...
class KernformProcessError(KernformNativeError): ...

def native_version() -> str: ...
def plan_initialization_json(
    intent_json: str,
    snapshot_json: str,
    catalog_json: str,
    files_json: str,
) -> str: ...
def inspect_repository_json(root: str, state_json: str | None) -> str: ...
def apply_plan_json(root: str, plan_json: str, new_project: bool) -> str: ...
def check_web_policy_json(files_json: str) -> str: ...
def render_capabilities_json(requested_json: str, variables_json: str) -> str: ...
def git_initial_commit_json(root: str, message: str) -> str: ...
def release_start_json(root: str, version: str, catalog_hash: str) -> str: ...
def release_inspect_json(root: str) -> str: ...
def release_verify_json(root: str, metadata_matches: bool, synchronized: bool) -> str: ...
def release_finalize_json(root: str, verification_complete: bool) -> str: ...
