schema = "kernform/v1"
generator_version = "0.1.0"

[project]
name = "example-api-web"
profile = "api"
capabilities = ["api", "ci", "locks-api", "nushell-agent", "nushell-human", "podman", "release", "web-server"]

[git]
enabled = false
initial_branch = "main"
initial_commit = false
create_remote = false

[versions]
policy = "newest-stable-exact"
allow_prerelease = false
catalog_id = "stable-2026-07-18-linux-amd64"
catalog_hash = "b83d3720ba10c51b49a5d349069b3cf194a613fdf813056e58b3fbc61675fb8b"

[web]
javascript = "none"

[containers]
engine = "podman"
rootless = true
